version: "3.7"
services:

  ws:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOCKER=1
      - XDEBUG_CONFIG=remote_host=host.docker.internal
      - MYSQL_DATABASE=feedz
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=db
    ports:
      - "8080:80"
        #    command: ["composer", "install"]
        #    command: ["composer", "update"]
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: library/mysql:8.0.20
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=feedz
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./resources/docker/config/my.cfg:/etc/mysql/conf.d/config-file.cnf"
      - "./resources/database/feedz.sql:/docker-entrypoint-initdb.d/1-schema.sql"
